apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
  labels:
    app: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener-api
          image: jamsheerply/url_shortener-api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: url-shortener-config
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  selector:
    app: url-shortener
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
